name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Use Node.js
      uses: actions/setup-node@v3.7.0
      with:
        node-version: 18
    - name: Update README.md
      run: |
        node index.js > README.md
    - name: Commit change & Push
      run: |
        git config user.name 'RimuruDev'
        git config user.email 'rimuru.dev@gmail.com'
        git commit -am "One step closer to vacation!!!"
        git push
